"""
copilot.py
CreditLens main orchestrator.
Combines: LightGBM prediction + SHAP evidence + RAG policy retrieval → LLM response.
The LLM is the last step. All quantitative values are computed before the LLM is called.
"""
import sys
import os
import json
import pandas as pd

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')))

from app.ml.explainer import CreditRiskExplainer
from app.rag.embeddings import EmbeddingModel
from app.rag.vector_store import VectorStore
from app.rag.retriever import Retriever
from app.services.financial_calc import compute_all_financial_metrics, classify_risk_probability
from app.services.prompts import (
    build_risk_explanation_prompt,
    build_customer_summary_prompt,
    build_policy_qa_prompt,
    build_combined_analysis_prompt,
)
from app.services.llm_provider import LLMProvider

# Hardcoded safety guard for LLM override attempts
REFUSAL_KEYWORDS = [
    "override the model",
    "ignore the probability",
    "change the risk score",
    "approve this customer",
    "reject this customer",
    "make the decision",
]

class CreditLensCopilot:
    def __init__(
        self,
        model_path: str,
        chroma_persist_dir: str,
        llm_provider: LLMProvider,
        embedding_model_name: str = "all-MiniLM-L6-v2",
    ):
        print("Initializing CreditLens Copilot...")
        self.explainer = CreditRiskExplainer(model_path)
        embedding_model = EmbeddingModel(model_name=embedding_model_name)
        vector_store = VectorStore(persist_dir=chroma_persist_dir)
        self.retriever = Retriever(vector_store, embedding_model)
        self.llm = llm_provider
        print("Copilot ready.")

    def _check_for_override_attempt(self, question: str) -> bool:
        """Returns True if the question is trying to get the LLM to override the ML model."""
        q_lower = question.lower()
        return any(kw in q_lower for kw in REFUSAL_KEYWORDS)

    def _build_structured_output(
        self,
        customer_id,
        shap_result: dict,
        financial_metrics: dict,
        policy_evidence: list,
        llm_text: str,
    ) -> dict:
        """Assembles the final structured JSON response."""
        return {
            "customer_id": str(customer_id),
            "risk_probability": round(shap_result["probability_of_default"], 4),
            "risk_category": classify_risk_probability(shap_result["probability_of_default"]),
            "shap_additivity_error": shap_result["additivity_error"],
            "top_risk_factors": shap_result["top_positive_contributors"],
            "risk_reducing_factors": shap_result["top_negative_contributors"],
            "financial_metrics": financial_metrics,
            "policy_evidence": [
                {
                    "document": r.get("document"),
                    "page": r.get("page"),
                    "excerpt": r.get("text", "")[:300],
                }
                for r in policy_evidence
            ],
            "llm_output": llm_text,
            "caveats": [
                "This output is generated by an AI assistant and is for analyst review only.",
                "The LightGBM model probability is authoritative; the LLM explanation is interpretive.",
                "Policy citations reference the demo knowledge base only.",
                "Do not use this output as the sole basis for a lending decision.",
            ],
        }

    def explain_risk(self, customer_df: pd.DataFrame, customer_id=None) -> dict:
        """Full risk explanation: LightGBM → SHAP → financial metrics → LLM explanation."""
        shap_result = self.explainer.explain_customer(customer_df)
        risk_category = classify_risk_probability(shap_result["probability_of_default"])
        financial_metrics = compute_all_financial_metrics(customer_df.iloc[0].to_dict())

        prompt = build_risk_explanation_prompt(
            probability=shap_result["probability_of_default"],
            risk_category=risk_category,
            top_positive=shap_result["top_positive_contributors"],
            top_negative=shap_result["top_negative_contributors"],
            financial_metrics=financial_metrics,
        )
        llm_text = self.llm.generate(prompt)
        return self._build_structured_output(customer_id or "unknown", shap_result, financial_metrics, [], llm_text)

    def customer_summary(self, customer_df: pd.DataFrame, customer_id=None) -> dict:
        """Full structured customer risk summary report."""
        shap_result = self.explainer.explain_customer(customer_df)
        risk_category = classify_risk_probability(shap_result["probability_of_default"])
        financial_metrics = compute_all_financial_metrics(customer_df.iloc[0].to_dict())

        prompt = build_customer_summary_prompt(
            customer_id=customer_id or "unknown",
            probability=shap_result["probability_of_default"],
            risk_category=risk_category,
            top_positive=shap_result["top_positive_contributors"],
            top_negative=shap_result["top_negative_contributors"],
            financial_metrics=financial_metrics,
        )
        llm_text = self.llm.generate(prompt)
        return self._build_structured_output(customer_id or "unknown", shap_result, financial_metrics, [], llm_text)

    def policy_qa(self, question: str) -> dict:
        """Policy Q&A: RAG retrieval → LLM grounded answer with citations."""
        if self._check_for_override_attempt(question):
            return {
                "query": question,
                "results": [],
                "llm_output": "This request appears to ask the AI to override the ML model's risk prediction or make an autonomous lending decision. CreditLens is not permitted to do this. The LightGBM model's prediction is authoritative. Please consult a human credit analyst for final decisions.",
                "caveats": ["Override attempt detected and blocked."],
            }
        retrieval = self.retriever.retrieve(question, top_k=3)
        retrieved_chunks = retrieval["results"]

        prompt = build_policy_qa_prompt(question=question, retrieved_chunks=retrieved_chunks)
        llm_text = self.llm.generate(prompt)

        return {
            "query": question,
            "policy_evidence": [
                {"document": r.get("document"), "page": r.get("page"), "excerpt": r.get("text", "")[:300]}
                for r in retrieved_chunks
            ],
            "llm_output": llm_text,
            "caveats": ["Policy evidence drawn from: Global Bank Retail Credit Policy (Demonstration Document — not a real regulatory publication)."],
        }

    def combined_analysis(self, question: str, customer_df: pd.DataFrame, customer_id=None) -> dict:
        """Full combined analysis: ML + SHAP + RAG + LLM in one response."""
        if self._check_for_override_attempt(question):
            return {
                "query": question,
                "llm_output": "This request appears to ask the AI to override the ML model or make a credit decision. CreditLens cannot do this.",
                "caveats": ["Override attempt blocked."],
            }

        shap_result = self.explainer.explain_customer(customer_df)
        risk_category = classify_risk_probability(shap_result["probability_of_default"])
        financial_metrics = compute_all_financial_metrics(customer_df.iloc[0].to_dict())

        retrieval = self.retriever.retrieve(question, top_k=3)
        retrieved_chunks = retrieval["results"]

        prompt = build_combined_analysis_prompt(
            question=question,
            probability=shap_result["probability_of_default"],
            risk_category=risk_category,
            top_positive=shap_result["top_positive_contributors"],
            top_negative=shap_result["top_negative_contributors"],
            financial_metrics=financial_metrics,
            retrieved_chunks=retrieved_chunks,
        )
        llm_text = self.llm.generate(prompt)
        return self._build_structured_output(customer_id or "unknown", shap_result, financial_metrics, retrieved_chunks, llm_text)
